// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"geektime/app/goods/internal/biz"
	"geektime/app/goods/internal/conf"
	"geektime/app/goods/internal/data"
	"geektime/app/goods/internal/server"
	"geektime/app/goods/internal/service"
	"geektime/pkg/appmanage"
)

// Injectors from wire.go:

func initApp(db *conf.ConfDB, http *conf.HttpConf, grpc *conf.GrpcConf, customer *conf.Customer) *appmanage.AppManage {
	fakeDB := data.NewBD(db)
	goodsRepo := data.NewGoodsRepo(fakeDB)
	customerClient := data.NewCustomerClient(customer)
	goodsUsecase := biz.NewGoodsUsecase(goodsRepo, customerClient)
	goodsService := service.NewGoodsService(goodsUsecase)
	httpServer := server.NewHttpServer(goodsService, http)
	grpcServer := server.NewGrpcServer(goodsService, grpc)
	appManage := appmanage.NewAppManage(httpServer, grpcServer)
	return appManage
}
