// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoodsServiceClient is the client API for GoodsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsServiceClient interface {
	FindGoods(ctx context.Context, in *FindGoodsRequest, opts ...grpc.CallOption) (*GoodsReply, error)
	SaleGoods(ctx context.Context, in *SaleGoodsRequest, opts ...grpc.CallOption) (*GoodsReply, error)
	NewGoods(ctx context.Context, in *NewGoodsRequest, opts ...grpc.CallOption) (*GoodsReply, error)
	DeleteGoods(ctx context.Context, in *DeleteGoodsRequest, opts ...grpc.CallOption) (*DeleteGoodsReply, error)
}

type goodsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsServiceClient(cc grpc.ClientConnInterface) GoodsServiceClient {
	return &goodsServiceClient{cc}
}

func (c *goodsServiceClient) FindGoods(ctx context.Context, in *FindGoodsRequest, opts ...grpc.CallOption) (*GoodsReply, error) {
	out := new(GoodsReply)
	err := c.cc.Invoke(ctx, "/goods.v1.GoodsService/FindGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) SaleGoods(ctx context.Context, in *SaleGoodsRequest, opts ...grpc.CallOption) (*GoodsReply, error) {
	out := new(GoodsReply)
	err := c.cc.Invoke(ctx, "/goods.v1.GoodsService/SaleGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) NewGoods(ctx context.Context, in *NewGoodsRequest, opts ...grpc.CallOption) (*GoodsReply, error) {
	out := new(GoodsReply)
	err := c.cc.Invoke(ctx, "/goods.v1.GoodsService/NewGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) DeleteGoods(ctx context.Context, in *DeleteGoodsRequest, opts ...grpc.CallOption) (*DeleteGoodsReply, error) {
	out := new(DeleteGoodsReply)
	err := c.cc.Invoke(ctx, "/goods.v1.GoodsService/DeleteGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsServiceServer is the server API for GoodsService service.
// All implementations must embed UnimplementedGoodsServiceServer
// for forward compatibility
type GoodsServiceServer interface {
	FindGoods(context.Context, *FindGoodsRequest) (*GoodsReply, error)
	SaleGoods(context.Context, *SaleGoodsRequest) (*GoodsReply, error)
	NewGoods(context.Context, *NewGoodsRequest) (*GoodsReply, error)
	DeleteGoods(context.Context, *DeleteGoodsRequest) (*DeleteGoodsReply, error)
	mustEmbedUnimplementedGoodsServiceServer()
}

// UnimplementedGoodsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoodsServiceServer struct {
}

func (UnimplementedGoodsServiceServer) FindGoods(context.Context, *FindGoodsRequest) (*GoodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindGoods not implemented")
}
func (UnimplementedGoodsServiceServer) SaleGoods(context.Context, *SaleGoodsRequest) (*GoodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaleGoods not implemented")
}
func (UnimplementedGoodsServiceServer) NewGoods(context.Context, *NewGoodsRequest) (*GoodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewGoods not implemented")
}
func (UnimplementedGoodsServiceServer) DeleteGoods(context.Context, *DeleteGoodsRequest) (*DeleteGoodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGoods not implemented")
}
func (UnimplementedGoodsServiceServer) mustEmbedUnimplementedGoodsServiceServer() {}

// UnsafeGoodsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsServiceServer will
// result in compilation errors.
type UnsafeGoodsServiceServer interface {
	mustEmbedUnimplementedGoodsServiceServer()
}

func RegisterGoodsServiceServer(s grpc.ServiceRegistrar, srv GoodsServiceServer) {
	s.RegisterService(&GoodsService_ServiceDesc, srv)
}

func _GoodsService_FindGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).FindGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.v1.GoodsService/FindGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).FindGoods(ctx, req.(*FindGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_SaleGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).SaleGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.v1.GoodsService/SaleGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).SaleGoods(ctx, req.(*SaleGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_NewGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).NewGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.v1.GoodsService/NewGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).NewGoods(ctx, req.(*NewGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_DeleteGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).DeleteGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.v1.GoodsService/DeleteGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).DeleteGoods(ctx, req.(*DeleteGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsService_ServiceDesc is the grpc.ServiceDesc for GoodsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goods.v1.GoodsService",
	HandlerType: (*GoodsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindGoods",
			Handler:    _GoodsService_FindGoods_Handler,
		},
		{
			MethodName: "SaleGoods",
			Handler:    _GoodsService_SaleGoods_Handler,
		},
		{
			MethodName: "NewGoods",
			Handler:    _GoodsService_NewGoods_Handler,
		},
		{
			MethodName: "DeleteGoods",
			Handler:    _GoodsService_DeleteGoods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/goods/v1/goods.proto",
}
